name: run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb scrot
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0201,C0114,C0115,C0116,W0611
    
    - name: Run the unittest
      run: |
        xvfb-run -a python test.py
        
    # Step 3: Start Xvfb and run the Python script
    - name: Start virtual display and run script
      run: |
        export DISPLAY=:99
        # Start the X virtual framebuffer in the background
        Xvfb :99 -screen 0 1280x1024x24 &

        # Allow some time for the virtual display to be set up
        sleep 5

        # Run your Python script (ensure it doesn't require interaction)
        python main.py

        # Now take a screenshot using scrot
        scrot /tmp/screenshot.png

    - name: Upload screenshot to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: /tmp/screenshot.png
